# in this folder run:
# docker-compose -p run1 up

version: '2'
services:
  mongo:
    image: "mongo:3.2.19-jessie"
    ports:
      - "27017:27017"

  web:
      build: .
#      online
#      user: "1001"
#      lokaal
      user: "502"
      volumes:
        - .:/app
      depends_on:
        - "mongo"
      links:
        - mongo
      ports:
        - 3001:3000
      command: node app.js
