# in this folder run:
# docker-compose -p run1 up

version: '2'
services:
  mongo:
    image: "mongo:3.2.19-jessie"
    ports:
      - "27018:27017"
    container_name: martijn_eyetracking_2019_mongo

  web:
      build: .
#      online
      user: "1001"
#      lokaal
#      user: "502"
      volumes:
        - .:/app
      depends_on:
        - "mongo"
      links:
        - mongo
      ports:
        - 3101:3000
      command: node app.js
      container_name: martijn_eyetracking_2019_node
