version: '3'
services:
  mongo:
    image: "mongo:3.2.19-jessie"
    ports:
      - "27018:27017"

  web:
      build: .
      volumes:
        - .:/app
      depends_on:
        - "mongo"
      links:
        - mongo
      ports:
        - 3001:3000
      command: node app.js
